services:
  - type: web
    name: portfolio-api
    runtime: docker
    plan: free
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    envVars:
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: EMAIL_RECIPIENT
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
